# Numpy Pratice
This is a simple repository of all essential Numpy commands for a quick primer. This will serve as quick lookup notes for those who do not know / understand Numpy and are trying to get into data science.

In [2]:
import numpy as np

In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
a=np.array([1,2,3,4,5,6,7,8,9],ndmin=3,dtype=complex, order='C')
print(a)
#ndmin- Number of dimensions of a numpy array
#dtype- contains the data type of the elements
#order- The order in which the array is stored. C is for row major, F is for column major

[[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j]]]


## Default datatypes
1. bool
2. int8, int16, int32, int64, intc (C style int)
3. uint8, uint16, uint32, uint64
4. float16, float32, float64 (default float)
5. complex64, complex128 (default) 
----------------------------------
you can use numbers from i1 to i4 to denote int sizes, f1 to f4 to denote float sizes and so on
You can also use s20, s30 etc to denote size of the byte string. Byte string is a string of bytes- can be used as character array to store character objects.

In [25]:
#Creating our own data types 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

[(b'abc', 21, 50.0) (b'xyz', 18, 75.0)]


In [34]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a.shape)
print(a)
print('-----------')
a.shape=(3,2)
print(a.shape)
print(a)
#This can also be achieved by using the reshape function. a=a.reshape(x,y)

(2, 3)
[[1 2 3]
 [4 5 6]]
-----------
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [49]:
a=np.arange(1,25,1)
print(a)
#arange(start, stop, step) starts from start to stop taking a step each time it goes in and creates 1D array 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [50]:
print(a.ndim) 
print(a)
print('--------------------')
a=a.reshape(3,2,4)
#The first arguement contains the number of dimensions
#The second arguement contains number of rows
#The thirt arguement contains number of columns
print(a.ndim)
print(a)

1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
--------------------
3
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [52]:
zarray=np.zeros([2,3],dtype='i4',order='C')
print(zarray)
#np.ones- Creates aray of 1s
#np.empty- creates empty array

[[0 0 0]
 [0 0 0]]


In [13]:
newarray=[(1,2,3),(4,5,6),(7,8,9)]  #all tuples should be of the same size
zarray=np.asarray(newarray,dtype='i2',order='F')
print(zarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### We cannot use the arange function to generate intervals in case of decimal numbers as it will not be able to generate nice intervals, so in order to do so we use different fucntion

In [19]:
#This is a more generalized and usable function instead of a quick fix 
karray=np.linspace(start=1, stop=25, num=40, endpoint=False, dtype='i2')
#start- the starting point
#stop- The stopping point
#num- the number of elements we need aka size of the array
#endpoint-Considers 25 as a endpoint if True or default else doesn't
#dtype- the type of data
print(karray)

[ 1  1  2  2  3  4  4  5  5  6  7  7  8  8  9 10 10 11 11 12 13 13 14 14 15
 16 16 17 17 18 19 19 20 20 21 22 22 23 23 24]


In [22]:
#we can also use this logspace for similar functionalisty
logarray=np.logspace(start=1, stop=25, num=50, endpoint=False, base=2, dtype='i2')
print(logarray)
#start and stop are the exponents i.e base to the poer of the start and base to the power of stop
#Rest everytihng is similar

[     2      2      3      5      7     10     14     20     28     39
     55     77    108    151    210    294    410    572    797   1112
   1552   2164   3019   4211   5873   8192  11425  15935  22226  31000
 -22299  -5231  18574 -13760  32549  31601  -9387 -14814  29356  11629
  24849 -23971 -16176  -8747 -29424    384  19549 -19238  12919   6064]


In [30]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a[1:3,1:3])
print('------------------')
print(a[::2])

[[4 5]
 [5 6]]
------------------
[[1 2 3]
 [4 5 6]]


In [35]:
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print(x[x>6]) #Yes, the variables need to be of the same name
print('------------------------')
print(x[1:4,[1,2]])

[ 7  8  9 10 11]
------------------------
[[ 4  5]
 [ 7  8]
 [10 11]]


The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.
Broadcasting is possible if the following rules are satisfied −

1. Array with smaller ndim than the other is prepended with '1' in its shape.

2. Size in each dimension of the output shape is maximum of the input sizes in that dimension.

2. An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.

4. If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

A set of arrays is said to be broadcastable if the above rules produce a valid result and one of the following is true −

1.  Arrays have exactly the same shape.

2.  Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.

3.  Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.
