# Deep Learning  
The input layer transfers data through synapses which have assigned weights (that is how ANNs work) and then we have the output layer. All input variables are independent to each other. We standardize the input values Output value can be numerical, binary or categorical dummy variables. 
The Neuron finds the weighted sum and applies activation function on it.
There are 4 different kinds of activation fucntion 
1. Threshhold function (Checks exactly if y=1)
2. The sigmoid fucntion or the logistic function - it is smoother than the threshhold function and tells us the probability that y=1 
3. Rectifier funtion- One of the most popular function. It is common to apply in the hidden layer. 
4. Hyperbolic tangent fucntion- The values go to below 0 so it is better.

## Here is a list of all activation fucntions 


![title](https://cdn-images-1.medium.com/max/1600/1*p_hyqAtyI8pbt2kEl6siOQ.png)

## What actually happens during training of the Nueral Network 

1. We initialize the weightys randomly (near 0, but not 0) 
2. Input the first layer, one feature per node 
3. **Forward Propagation**- From left to right such that impact of each neuron's activation is limited by it's weight. Propagate until you get the result Y 
4. Compare predicted value to actual value and measure the generated Error 
5. Back propagate the weights from right to left and update the weights according to how much they are responsible for the error (The learning rate decides by how much we update the values)
6. Repeat 1 to 5 
7. Redo more epochs 

![Steps](./Steps.png)

## Articles to study 
 
1. [A list of cost functions used in Neural Netwrok design](https://stats.stackexchange.com/questions/154879/a-list-of-cost-functions-used-in-neural-networks-alongside-applications) 
2. [An intution for gradient descent](https://iamtrask.github.io/2015/07/27/python-network-part2/)
3. [The book on Neural Nteowrk and deep maths associated with it](http://neuralnetworksanddeeplearning.com/)

## Problem 
A bank has a churn problem. Customers are leaving the bank. You are given a tiny sample of 10,000 customers and their details that was measured 6 months ago and you are responsible to know what is the reason of the churn and tell which customers are most likely to leave. The bank has measured after 6 months whether the customers left or are there and you have access to the data. 

In [8]:
# Data preprocessing first 
import pandas as pd
dataset=pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
dataset.shape

(10000, 14)

In [10]:
import numpy as np 
import matplotlib.pyplot as plt 
X=dataset.iloc[:,3:13].values
Y=dataset.iloc[:,13].values
X[0:10]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder1= LabelEncoder()
X[:,1]=labelencoder1.fit_transform(X[:,1])
X[0:10]

array([[619, 0, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 2, 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 0, 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 0, 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 2, 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 2, 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 0, 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 1, 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 0, 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 0, 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [12]:
labelencoder2= LabelEncoder()
X[:,2]=labelencoder1.fit_transform(X[:,2])
X[0:10]

array([[619, 0, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 2, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 0, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 0, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 2, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 2, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 0, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 1, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 0, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 0, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]], dtype=object)

In [13]:
onehotencoder=OneHotEncoder(categorical_features=[1])
X=onehotencoder.fit_transform(X).toarray()
pd.DataFrame(X).head()

0    1    2      3    4     5    6          7    8    9    10         11
0  1.0  0.0  0.0  619.0  0.0  42.0  2.0       0.00  1.0  1.0  1.0  101348.88
1  0.0  0.0  1.0  608.0  0.0  41.0  1.0   83807.86  1.0  0.0  1.0  112542.58
2  1.0  0.0  0.0  502.0  0.0  42.0  8.0  159660.80  3.0  1.0  0.0  113931.57
3  1.0  0.0  0.0  699.0  0.0  39.0  1.0       0.00  2.0  0.0  0.0   93826.63
4  0.0  0.0  1.0  850.0  0.0  43.0  2.0  125510.82  1.0  1.0  1.0   79084.10

In [14]:
# Now to avoid falling into the ummy variable trap we remove one dummy variable 
X= X[:,1:]
pd.DataFrame(X)

0    1      2    3     4     5          6    7    8    9          10
0     0.0  0.0  619.0  0.0  42.0   2.0       0.00  1.0  1.0  1.0  101348.88
1     0.0  1.0  608.0  0.0  41.0   1.0   83807.86  1.0  0.0  1.0  112542.58
2     0.0  0.0  502.0  0.0  42.0   8.0  159660.80  3.0  1.0  0.0  113931.57
3     0.0  0.0  699.0  0.0  39.0   1.0       0.00  2.0  0.0  0.0   93826.63
4     0.0  1.0  850.0  0.0  43.0   2.0  125510.82  1.0  1.0  1.0   79084.10
5     0.0  1.0  645.0  1.0  44.0   8.0  113755.78  2.0  1.0  0.0  149756.71
6     0.0  0.0  822.0  1.0  50.0   7.0       0.00  2.0  1.0  1.0   10062.80
7     1.0  0.0  376.0  0.0  29.0   4.0  115046.74  4.0  1.0  0.0  119346.88
8     0.0  0.0  501.0  1.0  44.0   4.0  142051.07  2.0  0.0  1.0   74940.50
9     0.0  0.0  684.0  1.0  27.0   2.0  134603.88  1.0  1.0  1.0   71725.73
10    0.0  0.0  528.0  1.0  31.0   6.0  102016.72  2.0  0.0  0.0   80181.12
11    0.0  1.0  497.0  1.0  24.0   3.0       0.00  2.0  1.0  0.0   76390.01
12    0.0  0.0  476.0  0.0  34.0  10.0       0.00  2.0  1.0  0.0   26260.98
13    0.0  0.0  549.0  0.0  25.0   5.0       0.00  2.0  0.0  0.0  190857.79
14    0.0  1.0  635.0  0.0  35.0   7.0       0.00  2.0  1.0  1.0   65951.65
15    1.0  0.0  616.0  1.0  45.0   3.0  143129.41  2.0  0.0  1.0   64327.26
16    1.0  0.0  653.0  1.0  58.0   1.0  132602.88  1.0  1.0  0.0    5097.67
17    0.0  1.0  549.0  0.0  24.0   9.0       0.00  2.0  1.0  1.0   14406.41
18    0.0  1.0  587.0  1.0  45.0   6.0       0.00  1.0  0.0  0.0  158684.81
19    0.0  0.0  726.0  0.0  24.0   6.0       0.00  2.0  1.0  1.0   54724.03
20    0.0  0.0  732.0  1.0  41.0   8.0       0.00  2.0  1.0  1.0  170886.17
21    0.0  1.0  636.0  0.0  32.0   8.0       0.00  2.0  1.0  0.0  138555.46
22    0.0  1.0  510.0  0.0  38.0   4.0       0.00  1.0  1.0  0.0  118913.53
23    0.0  0.0  669.0  1.0  46.0   3.0       0.00  2.0  0.0  1.0    8487.75
24    0.0  0.0  846.0  0.0  38.0   5.0       0.00  1.0  1.0  1.0  187616.16
25    0.0  0.0  577.0  1.0  25.0   3.0       0.00  2.0  0.0  1.0  124508.29
26    1.0  0.0  756.0  1.0  36.0   2.0  136815.64  1.0  1.0  1.0  170041.95
27    0.0  0.0  571.0  1.0  44.0   9.0       0.00  2.0  0.0  0.0   38433.35
28    1.0  0.0  574.0  0.0  43.0   3.0  141349.43  1.0  1.0  1.0  100187.43
29    0.0  0.0  411.0  1.0  29.0   0.0   59697.17  2.0  1.0  1.0   53483.21
...   ...  ...    ...  ...   ...   ...        ...  ...  ...  ...        ...
9970  0.0  0.0  518.0  1.0  42.0   7.0  151027.05  2.0  1.0  0.0  119377.36
9971  0.0  0.0  833.0  0.0  34.0   3.0  144751.81  1.0  0.0  0.0  166472.81
9972  0.0  0.0  758.0  1.0  26.0   4.0  155739.76  1.0  1.0  0.0  171552.02
9973  0.0  0.0  611.0  1.0  27.0   7.0       0.00  2.0  1.0  1.0  157474.10
9974  0.0  0.0  583.0  1.0  33.0   7.0  122531.86  1.0  1.0  0.0   13549.24
9975  1.0  0.0  610.0  1.0  50.0   1.0  113957.01  2.0  1.0  0.0  196526.55
9976  0.0  0.0  637.0  0.0  33.0   7.0  103377.81  1.0  1.0  0.0   84419.78
9977  0.0  0.0  683.0  0.0  32.0   9.0       0.00  2.0  1.0  1.0   24991.92
9978  0.0  0.0  774.0  1.0  40.0   9.0   93017.47  2.0  1.0  0.0  191608.97
9979  0.0  0.0  677.0  0.0  58.0   1.0   90022.85  1.0  0.0  1.0    2988.28
9980  0.0  1.0  741.0  1.0  35.0   6.0   74371.49  1.0  0.0  0.0   99595.67
9981  1.0  0.0  498.0  1.0  42.0   3.0  152039.70  1.0  1.0  1.0   53445.17
9982  1.0  0.0  655.0  0.0  46.0   7.0  137145.12  1.0  1.0  0.0  115146.40
9983  0.0  0.0  613.0  1.0  40.0   4.0       0.00  1.0  0.0  0.0  151325.24
9984  1.0  0.0  602.0  1.0  35.0   7.0   90602.42  2.0  1.0  1.0   51695.41
9985  0.0  0.0  659.0  1.0  36.0   6.0  123841.49  2.0  1.0  0.0   96833.00
9986  1.0  0.0  673.0  1.0  47.0   1.0  183579.54  2.0  0.0  1.0   34047.54
9987  0.0  1.0  606.0  1.0  30.0   8.0  180307.73  2.0  1.0  1.0    1914.41
9988  0.0  0.0  775.0  1.0  30.0   4.0       0.00  2.0  1.0  0.0   49337.84
9989  0.0  1.0  841.0  1.0  28.0   4.0       0.00  2.0  1.0  1.0  179436.60
9990  1.0  0.0  714.0  1.0  33.0   3.0   35016.60  1.0 

In [15]:
X[1]

array([0.0000000e+00, 1.0000000e+00, 6.0800000e+02, 0.0000000e+00,
       4.1000000e+01, 1.0000000e+00, 8.3807860e+04, 1.0000000e+00,
       0.0000000e+00, 1.0000000e+00, 1.1254258e+05])

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test=sc.transform(X_test)
pd.DataFrame(X_test)

0         1         2         3         4         5         6   \
0     1.754865 -0.573694 -0.552043 -1.091687 -0.368904  1.044737  0.879303   
1    -0.569844 -0.573694 -1.314903 -1.091687  0.109617 -1.031415  0.429722   
2    -0.569844  1.743090  0.571630 -1.091687  0.301026  1.044737  0.308583   
3    -0.569844 -0.573694  1.416961  0.916013 -0.656016 -0.339364  0.575336   
4     1.754865 -0.573694  0.571630  0.916013 -0.081791  0.006661  1.389611   
5    -0.569844  1.743090  0.200509 -1.091687  1.736588 -0.685390  1.590021   
6    -0.569844  1.743090 -0.624205  0.916013 -0.464608 -1.723466 -0.164023   
7    -0.569844  1.743090 -0.149995 -1.091687 -0.943129  0.352686  1.302385   
8    -0.569844 -0.573694 -0.541734 -1.091687  2.406518  1.390762 -1.215717   
9    -0.569844 -0.573694 -2.005601 -1.091687  2.310814 -1.377440  1.426618   
10   -0.569844 -0.573694 -1.572626 -1.091687 -0.751721  1.736788 -1.215717   
11   -0.569844  1.743090  0.654101  0.916013  0.588138  1.044737  1.195699   
12    1.754865 -0.573694 -1.675715 -1.091687 -0.560312 -0.339364  1.021548   
13    1.754865 -0.573694 -0.912855 -1.091687 -0.751721  1.390762  0.656410   
14    1.754865 -0.573694  1.252019 -1.091687  1.162363  1.390762  1.084327   
15    1.754865 -0.573694  0.169582  0.916013  1.545180  1.390762  1.251520   
16   -0.569844 -0.573694 -1.417992 -1.091687  0.396730  1.390762 -1.215717   
17   -0.569844  1.743090  0.252053  0.916013  2.597926  0.006661  0.632464   
18   -0.569844 -0.573694 -0.294320 -1.091687 -0.847425 -0.339364  0.508211   
19   -0.569844 -0.573694 -1.026253 -1.091687  0.588138  0.352686 -1.215717   
20    1.754865 -0.573694  0.128346  0.916013  0.301026  0.698712  0.636881   
21   -0.569844 -0.573694  2.056114  0.916013 -0.368904 -1.031415 -1.215717   
22   -0.569844  1.743090 -1.015944 -1.091687 -0.464608 -0.339364 -1.215717   
23   -0.569844 -0.573694 -2.129308  0.916013 -0.464608 -1.031415  1.090528   
24   -0.569844 -0.573694  1.478815  0.916013 -0.368904  0.352686 -1.215717   
25   -0.569844  1.743090  1.819009  0.916013  0.683842 -1.377440  1.713074   
26   -0.569844  1.743090 -0.624205 -1.091687 -0.943129 -1.031415  1.451869   
27    1.754865 -0.573694 -1.634480 -1.091687 -0.847425  1.736788  0.017456   
28   -0.569844 -0.573694 -1.572626 -1.091687 -0.943129  1.390762 -1.215717   
29   -0.569844 -0.573694  1.097385 -1.091687  0.492434 -0.339364  0.754995   
...        ...       ...       ...       ...       ...       ...       ...   
1970 -0.569844  1.743090 -0.108759  0.916013  0.779547  0.352686  0.207273   
1971 -0.569844  1.743090 -0.273702  0.916013  0.683842 -0.685390 -1.215717   
1972  1.754865 -0.573694  0.097419  0.916013 -1.038833 -1.377440  0.676374   
1973 -0.569844  1.743090  0.726264  0.916013 -0.081791  0.698712 -1.215717   
1974 -0.569844 -0.573694  1.571595  0.916013 -0.560312  0.352686 -1.215717   
1975 -0.569844 -0.573694 -1.108725 -1.091687  3.076447 -1.377440  0.451157   
1976 -0.569844  1.743090  0.633483  0.916013  0.779547 -1.377440  1.019704   
1977 -0.569844 -0.573694  0.654101  0.916013 -0.464608  0.006661  1.040255   
1978 -0.569844 -0.573694  0.468540  0.916013 -1.134537 -0.339364  0.184743   
1979 -0.569844 -0.573694  0.664410  0.916013 -1.038833  0.698712  1.347132   
1980 -0.569844  1.743090 -1.263358  0.916013  0.396730  0.698712  0.341934   
1981 -0.569844 -0.573694 -1.191196 -1.091687  0.970955 -0.685390 -1.215717   
1982 -0.569844 -0.573694 -1.325212  0.916013  0.205321  0.006661  1.087791   
1983 -0.569844  1.743090 -1.263358  0.916013 -1.517354  0.698712  0.458126   
1984 -0.569844 -0.573694 -0.778839  0.916013 -0.943129 -0.339364  0.731044   
1985 -0.569844  1.743090 -0.222157  0.916013  0.205321  1.736788  1.183685   
1986 -0.569844  1.743090 -1.294285 -1.091687 -1.325946  1.736788 -1.215717   
1987 -0.569844 -0.573694 -1.438610  0.916013 -1.134537  1.044737 -1.215717   
1988 -0.569844 -0.573694  0.499467  0.916013  0.492434  1.044737  1.320302   
1989 -0.569844  1.743090 -0.696368

## Making the Artificial Neural Network 

We can define our Neural Network as a sequence or as a graph

In [1]:
import keras

Using TensorFlow backend.


In [2]:
from keras.models import Sequential
from keras.layers import Dense

In [23]:
classifier= Sequential()
# Step 1 - Dense layer will take care of random initialization. 
# We chose relu for hidden and sigmoid for output 
# Initially we chose the average of input and output as the dimension of hidden layers 
#Specify the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [24]:
#The next layer knows the number of inputs
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [25]:
#Creating the output layer
# Our output is a binary value
#If there is a multiclass classification, change the activation function to softmax which is sigmoid for higher dimensions
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [26]:
# Compiling Neural Network- STochastic graidentr descent on Neural NEtwork
# We need to optimize loss fucntion to get the values 
# The loss fucntion will be for the output layer that is logistic loss i.e. binary cross entropy or cateogrical cross entropy
# The metric defines the accuracy metric- this expects a list of metrics
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [28]:
# Give epochs and batch size
classifier.fit(X_train, Y_train, batch_size = 10, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 2s 236us/step - loss: 0.4846 - acc: 0.7956
Epoch 2/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.4300 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4250 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.4210 - acc: 0.8102
Epoch 5/100
8000/8000 [==============================] - 1s 182us/step - loss: 0.4184 - acc: 0.8240
Epoch 6/100
8000/8000 [==============================] - 1s 181us/step - loss: 0.4164 - acc: 0.8262
Epoch 7/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.4147 - acc: 0.8301
Epoch 8/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.4131 - acc: 0.8297
Epoch 9/100
8000/8000 [==============================] - 1s 175us/step - loss: 0.4119 - acc: 0.8310
Epoch 10/100
8000/8000 [==============================] - 1s 180us/step - loss: 0.4112 - acc: 0.8314

8000/8000 [==============================] - 2s 230us/step - loss: 0.3975 - acc: 0.8364
Epoch 83/100
8000/8000 [==============================] - 2s 221us/step - loss: 0.3976 - acc: 0.8359
Epoch 84/100
8000/8000 [==============================] - 2s 237us/step - loss: 0.3980 - acc: 0.8332
Epoch 85/100
8000/8000 [==============================] - 2s 224us/step - loss: 0.3973 - acc: 0.8345
Epoch 86/100
8000/8000 [==============================] - 2s 218us/step - loss: 0.3978 - acc: 0.8350
Epoch 87/100
8000/8000 [==============================] - 2s 227us/step - loss: 0.3972 - acc: 0.8355
Epoch 88/100
8000/8000 [==============================] - 2s 225us/step - loss: 0.3975 - acc: 0.8346
Epoch 89/100
8000/8000 [==============================] - 2s 224us/step - loss: 0.3973 - acc: 0.8351
Epoch 90/100
8000/8000 [==============================] - 2s 236us/step - loss: 0.3972 - acc: 0.8365
Epoch 91/100
8000/8000 [==============================] - 2s 239us/step - loss: 0.3974 - acc: 0.8357
Epo

In [33]:
Y_pred= classifier.predict(X_test)
Y_pred = (Y_pred > 0.5)
Y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [35]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(Y_test,Y_pred)
cm

array([[1536,   59],
       [ 260,  145]])

In [38]:
# We get an accuracy of this much on the test dataset
(1536+145)/2000

0.8405

In [42]:
# Now let us see if the model performs on a completely new data element 
"""
    Geography: France
    Credit Score: 600
    Gender: Male
    Age: 40 years old
    Tenure: 3 years
    Balance: $60000
    Number of Products: 2
    Does this customer have a credit card ? Yes
    Is this customer an Active Member: Yes
    Estimated Salary: $50000 """
new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))) 
# Double brackets for horizontal layer
# sc.transform for rescaling the values
new_prediction = (new_prediction >0.5)
new_prediction

array([[False]])

### So this customer didn't leave the bank. Problem solved 

Now we come across the fact that repeated training of the Network yeilds different values. So we need to understand how to tune the values of the network in order to have an efficient training. In order to do so we use K-Fold cross validation which is used in the bias variance trade off understanding. 

In this we divide the model into k folds and we train on the k-1 and use the kth one as the test, k times so we can get the best bias and variance 

In [44]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
# We use this in order to use the scikit learn function with the keras model 

In [45]:
# We need to define a function that builds the classifier that we need to measure
def build_classifier():
    classifier2= Sequential()
    classifier2.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier2.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier2.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier2.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier2

In [ ]:
# Now we need a global classifier that we can work on 
classifier_global = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 100)
# n_jobs defines how many CPUs to use. -1 for all CPUs 
accuracies = cross_val_score(estimator = classifier_global, X=X_train, y=Y_train, cv=10, n_jobs= 2, verbose= True )
# This did not execute on my device for some odd reason.