## Multiple Regression
This notebook contains model for Multiple regression 

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split

## Problem
you have 50 companies in total. You have several data on them. You have to analyze the data for a venture capital firm in order to judge what kind of company should they be interested in. You have to analyze which spend yeilds more profit. 

In [3]:
dataset= pd.read_csv("MultipleRegression.csv")
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

## Assumptions of a Linear Regression model 

1. Linearity 
2. Homoscendasticity 
3. Multivariate Normality 
4. Independence of errors 
5. Lack of multicollinearity

-------------------------------------------

#### Dummy Variable Trap

We do not include all dummy variables. 

#### Why don't we use all variables 

Some are garbage variables which do not predict something 

#### How to select models 
1. **All in**- Throw in all variables. You do this when you need to or you are preparing for backward elimination 


2. **Backward elimination** - We select a significance level for a variable to stay in the model. You fit all predictors in the model and calculte the p-value. You delete the model with highest p value if it is greater than the significance level and you re fit the whole model and repeat the step until the highest loss possible (p value) is still less than the decided significance level. 


3. **Forward selection** - Sameway as Backward elimination but chosing an entry significance level and chosing out of all relations. Keep the previous model

![FS](ForwardSelection.png)

4. **Bidirectional elimination** - 

![BD](Bidirectional.png)

5. **Score comparison**- Create all models and compare 

We use Backward elimination because it is fast

**Stepwise regression**- 2,3,4 are together called Stepwise regression 

In [20]:
X= dataset.iloc[:,:-1].values
Y=dataset.iloc[:,4].values
le= LabelEncoder()
X[:,3]=le.fit_transform(X[:,3])
ohe= OneHotEncoder(categorical_features=[3])
X=ohe.fit_transform(X).toarray()
pd.DataFrame(X).head()

0    1    2          3          4          5
0  0.0  0.0  1.0  165349.20  136897.80  471784.10
1  1.0  0.0  0.0  162597.70  151377.59  443898.53
2  0.0  1.0  0.0  153441.51  101145.55  407934.54
3  0.0  0.0  1.0  144372.41  118671.85  383199.62
4  0.0  1.0  0.0  142107.34   91391.77  366168.42

In [21]:
# Avoid the dummy varibale trap 
X=X[:,1:]
pd.DataFrame(X).head()

0    1          2          3          4
0  0.0  1.0  165349.20  136897.80  471784.10
1  0.0  0.0  162597.70  151377.59  443898.53
2  1.0  0.0  153441.51  101145.55  407934.54
3  0.0  1.0  144372.41  118671.85  383199.62
4  1.0  0.0  142107.34   91391.77  366168.42

In [10]:
X_train, X_test, Y_train, Y_test= train_test_split(X,Y,test_size= 0.2, random_state=0)

In [11]:
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [12]:
regressor.predict(X_test)

array([103015.20159796, 132582.27760815, 132447.73845175,  71976.09851258,
       178537.48221056, 116161.24230166,  67851.69209676,  98791.73374687,
       113969.43533013, 167921.06569551])

In [13]:
Y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [22]:
regressor.score(X_test, Y_test)

0.9347068473282446

In [16]:
regressor.coef_

array([-9.59284160e+02,  6.99369053e+02,  7.73467193e-01,  3.28845975e-02,
        3.66100259e-02])

In [23]:
# Backward Elimination 
import statsmodels.formula.api as sm
# We need to add a column of 1st to our model. Why we do that because in our equataion of ax1 + bx2 + cx3 + dx4 
X=np.append(arr=np.ones((50,1)).astype(int), values=X, axis=1)
pd.DataFrame(X).head()

0    1    2          3          4          5
0  1.0  0.0  1.0  165349.20  136897.80  471784.10
1  1.0  0.0  0.0  162597.70  151377.59  443898.53
2  1.0  1.0  0.0  153441.51  101145.55  407934.54
3  1.0  0.0  1.0  144372.41  118671.85  383199.62
4  1.0  1.0  0.0  142107.34   91391.77  366168.42

In [25]:
X_opt= X[:,:]
SL= 0.05
regresoor_ols= sm.OLS()

TypeError: __init__() missing 1 required positional argument: 'endog'